<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Kapil" failures="2" tests="3" name="Test(failed)" time="16.389" errors="0" timestamp="2023-10-29T20:14:16 IST">
  <testcase classname="testCases.InventoryPageTest" name="verifyNumElementCartTest" time="1.897">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;6&amp;gt; but was:&amp;lt;4&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<6> but was:<4>
at testCases.InventoryPageTest.verifyNumElementCartTest(InventoryPageTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyNumElementCartTest -->
  <testcase classname="testCases.InventoryPageTest" name="VerifyProductLabelTest" time="0.129">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;https://www.saucedemo.com/cart.html&amp;gt; but was:&amp;lt;Products&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<https://www.saucedemo.com/cart.html> but was:<Products>
at testCases.InventoryPageTest.VerifyProductLabelTest(InventoryPageTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- VerifyProductLabelTest -->
  <testcase classname="testCases.LoginPageTest" name="loginToAppTest" time="0.532"/>
  <testcase classname="testCases.LoginPageTest" name="verifyTitleOfApplication" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleOfApplication -->
  <testcase classname="testCases.LoginPageTest" name="verifyURLofApplication" time="0.0">
    <ignored/>
  </testcase> <!-- verifyURLofApplication -->
  <testcase classname="testCases.InventoryPageTest" name="removeToCartTest" time="0.0">
    <ignored/>
  </testcase> <!-- removeToCartTest -->
  <testcase classname="testCases.InventoryPageTest" name="VerifyTwitterLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyTwitterLogoTest -->
</testsuite> <!-- Test(failed) -->
